version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_API_URL=http://localhost:8001
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - 8001:8001
